// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.Mistral.AzureSdk;
using Microsoft.SemanticKernel.Http;

#pragma warning disable CA2208 // Instantiate argument exceptions correctly

namespace Microsoft.SemanticKernel.Connectors.Mistral;

/// <summary>
/// Base class for AI clients that provides common functionality for interacting with OpenAI services.
/// </summary>
internal class ClientCore
{
    private const int MaxResultsPerPrompt = 128;

    internal ClientCore(string modelName, string apiKey, HttpClient httpCient = null)
    {
        _apiKey = apiKey;
        this._httpCient = httpCient;
        DeploymentOrModelName = modelName;
        
    }

    /// <summary>
    /// Model Id or Deployment Name
    /// </summary>
    internal string DeploymentOrModelName { get; set; } = string.Empty;

    /// <summary>
    /// Logger instance
    /// </summary>
    internal ILogger Logger { get; set; }

    private string _apiKey;
    private HttpClient _httpCient;

    /// <summary>
    /// Storage for AI service attributes.
    /// </summary>
    internal Dictionary<string, object?> Attributes { get; } = new();

    /// <summary>
    /// Creates completions for the prompt and settings.
    /// </summary>
    /// <param name="text">The prompt to complete.</param>
    /// <param name="executionSettings">Execution settings for the completion API.</param>
    /// <param name="kernel">The <see cref="Kernel"/> containing services, plugins, and other state for use throughout the operation.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>Completions generated by the remote model</returns>
    internal async Task<IReadOnlyList<TextContent>> GetTextResultsAsync(
        string text,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        CancellationToken cancellationToken = default)
    {
        ChatHistory history = new ChatHistory();
        history.AddUserMessage(text);
        var chatResult = await GetChatMessageContentsAsync(history, executionSettings, kernel, cancellationToken).ConfigureAwait(false);
        return chatResult.Select(choice => new TextContent(choice.Content, this.DeploymentOrModelName, choice, Encoding.UTF8, choice.Metadata)).ToList();

    }

    internal  IAsyncEnumerable<StreamingTextContent> GetStreamingTextContentsAsync(
        string prompt,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        throw new Exception("Not supported by API");
    }

    /// <summary>
    /// Generate a new chat message
    /// </summary>
    /// <param name="chat">Chat history</param>
    /// <param name="executionSettings">Execution settings for the completion API.</param>
    /// <param name="kernel">The <see cref="Kernel"/> containing services, plugins, and other state for use throughout the operation.</param>
    /// <param name="cancellationToken">Async cancellation token</param>
    /// <returns>Generated chat message in string format</returns>
    internal async Task<IReadOnlyList<ChatMessageContent>> GetChatMessageContentsAsync(
        ChatHistory chat,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        CancellationToken cancellationToken = default)
    {
       
        // Make the request.
        var responseData = await CallMistralAsync(chat).ConfigureAwait(false);

        ChatMessageContent content = new ChatMessageContent(AuthorRole.Assistant, responseData.choices[0].message.content);

        IReadOnlyDictionary<string, object> metadata = new Dictionary<string, object>()
        {
            {"Usage", responseData.usage }
        };
        return responseData.choices.Select(chatChoice => new ChatMessageContent(
           role: AuthorRole.Assistant,
           content: chatChoice.message.content,
            modelId: responseData.model,
            metadata: metadata
         )).ToList();
    }

    private async Task<MistralAIApiResponse> CallMistralAsync(ChatHistory chat)
    {
        string url = "https://api.mistral.ai/v1/chat/completions";
        List<Message> messages = new List<Message>();
        foreach(var msg in chat)
        {
            string role = "assistant";
            if (msg.Role == AuthorRole.User) role = "user";
            if (msg.Role == AuthorRole.System) role = "system";
            messages.Add(new Message { role = role, content = msg.Content });
        }

        //hack: the API does not like system-only requests
        if(messages.Last().role != "user") messages.Last().role = "user";

        MistralAiApiRequest request = new MistralAiApiRequest {
            model = DeploymentOrModelName,
            safe_mode = true,
            messages = messages.ToArray()
        };

        if (_httpCient == null)
        {
            _httpCient = new HttpClient();
        }
        _httpCient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);
        var content = new StringContent(JsonSerializer.Serialize(request), Encoding.UTF8, "application/json");
       var response = await _httpCient.PostAsync(url, content).ConfigureAwait(false);
        var responseContent = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
      
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpOperationException(response.StatusCode, responseContent, response.ReasonPhrase, new HttpRequestException());
        }

        MistralAIApiResponse result = JsonSerializer.Deserialize< MistralAIApiResponse>(responseContent);
        return result;
    }

    internal  IAsyncEnumerable<StreamingChatMessageContent> GetStreamingChatMessageContentsAsync(
        ChatHistory chat,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        throw new Exception("Not supported by API");
    }

    internal  IAsyncEnumerable<StreamingTextContent> GetChatAsTextStreamingContentsAsync(
        string prompt,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        throw new Exception("Not supported by API");
    }

    internal async Task<IReadOnlyList<TextContent>> GetChatAsTextContentsAsync(
        string text,
        PromptExecutionSettings? executionSettings,
        Kernel? kernel,
        CancellationToken cancellationToken = default)
    {

        ChatHistory chat = new ChatHistory();
        chat.AddUserMessage(text);
        return (await this.GetChatMessageContentsAsync(chat, executionSettings, kernel, cancellationToken).ConfigureAwait(false))
            .Select(chat => new TextContent(chat.Content, chat.ModelId, chat.Content, Encoding.UTF8, chat.Metadata))
            .ToList();
    }

    internal void AddAttribute(string key, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            this.Attributes.Add(key, value);
        }
    }
}

